repos:
  # 🔹 Black: auto-formats Python code
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # 🔹 Ruff: super-fast linter & formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
      - id: ruff-format

  # 🔹 Mypy: static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  # 🔹 Basic safety checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
